# version: '3.8'
 
services:
  netbootxyz:
    image: netbootxyz/netbootxyz:latest
    container_name: netbootxyz
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    restart: unless-stopped